### ISSUE TITLE
Protege plugin

### ISSUE THREAD

**Issue by robclouth** [julianmendez/born#6]
Hi, I'm trying to use the protege plugin but BORN doesn't appear in the reasoners list or anywhere else. It is shown in the plugins list though.
I'm using protege 5.

**Comment by buoncubi** [comment]
Hi, same problem here, do you have any suggestions?

 The logs I've got from protege 5.1.0 are:
```
Error starting file:/opt/protege/plugins/de.tu-dresden.inf.lat.born-0.2.0.jar 
org.osgi.framework.BundleException: Unresolved constraint in bundle de.tu-dresden.inf.lat.born [24]: Unable to resolve 24.0: missing requirement [24.0] osgi.wiring.package; (&(osgi.wiring.package=de.uulm.ecs.ai.owlapi.krssrenderer)(version>=3.5.0)(!(version>=4.0.0)))
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2045) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304) [org.apache.felix.main.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

**Comment by robclouth** [comment]
I never solved it...

**Comment by buoncubi** [comment]
It seems I have found a solution. I don't know if it is the best but it fixes the error. 

Download the sources and install the maven (follow: https://github.com/julianmendez/born#source-code).  Than, just copy `born/born-plugin/target/de.tu-dresden.inf.lat.born-<VERIOSN>-SNAPSHOT.jar`into the protege plugin folder.

Now I can see the plugin in protege but still I don't know how to use it. 
Any hints are very appreciated.

**Comment by julianmendez** [comment]
Hi!
BORN 0.3.0 has been already released. This version is compatible with Protege 5.0.0 .
Please, let me know if this solves the issue.
Thank you!

**Comment by julianmendez** [comment]
Hi!
BORN 0.4.1 is compatible with Protege 5.5.0, and also runs in Protege 5.6.3.
It requires to have Python 3 installed.
